name: Deploy to Netlify on commits to deploy
on:
  push:
    branches: [deploy]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Pulls in WASM Pack
      - uses: jetli/wasm-pack-action@v0.3.0

      - name: Run WASM Pack
        run: wasm-pack build --target web

      - name: Copy library into www
        run: cp -R pkg/ www/pkg

      - name: Deploying Site
        env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=www --prod